---
- name: Install rsyslog
  yum:
    name:
      - rsyslog
    update_cache: yes
    state: present

- name: Copy rsyslog configuration file
  template:
      src: "templates/rsyslog.conf.j2" 
      dest: "/etc/rsyslog.conf" 
      force: yes
  notify: restart rsyslog
...
