# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"

    config.vm.define "webcentos" do |webcentos|
      webcentos.vm.box = "centos/7"
      webcentos.vm.hostname = "webcentos.lab.loc"
      webcentos.vm.network "private_network", ip: "10.0.10.3"
      ssh_insecure_key_pub = File.readlines("ssh_insecure_key/key.pub").first.strip
      webcentos.vm.provision "shell", inline: <<-SHELL
      echo #{ssh_insecure_key_pub} >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end

    config.vm.define "ans" do |ans|
      ans.vm.box = "centos/7"
      ans.vm.hostname = "ans.lab.loc"
      ans.vm.network "private_network", ip: "10.0.10.2"
      ans.vm.provision "shell", inline: <<-SHELL
      cp /vagrant/ssh_insecure_key/key /home/vagrant/.ssh/id_rsa
      chown vagrant /home/vagrant/.ssh/id_rsa
      chmod 400 /home/vagrant/.ssh/id_rsa
      SHELL
      ans.vm.provision "shell", path: "provision.sh"
      ans.vm.synced_folder "playbooks", "/home/vagrant/playbooks", type: "virtualbox"
    end
end
