---
- name: Configure FreeIPA server
  hosts: dc
  become: True
  tags:
    - servers
  roles:
    - role: FreeIPA
      ipa_domain: lab.loc
      ipa_realm: LAB.LOC

- name: Configure ipa client
  hosts: client
  tags:
    - client
  become: True
  gather_facts: False
  roles:
    - role: ipa-client
      ipa_domain: lab.loc
      ipa_realm: LAB.LOC
      ipa_server_name: dc01.lab.loc
      ipa_server_ip: 10.0.10.3
      hostname: hw10.lab.loc
