---
- name: setup packages for ipa client
  yum:
    name: ipa-client
    state: present

- name: Loop DNS requests on current server
  template:
      dest: "/etc/resolv.conf"
      src: "templates/resolv.conf.j2"
      force: yes

- name: Stop and disabled chronyd
  service:
      name: chronyd
      state: stopped
      enabled: no

- name: setup ipa client
  command: >
    ipa-client-install -U \
      -p admin \
      -w password \
      --server={{ ipa_server_name }} \
      --ip-address={{ ipa_server_ip }} \
      --domain={{ ipa_domain }} \
      --realm={{ ipa_realm }} \
      --hostname={{ hostname }} \
      --mkhomedir
  args:
    creates: /etc/ipa/default.conf
...
